CREATE TABLE address_book_items ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "owner_person_id" integer DEFAULT NULL, "entry_person_id" integer DEFAULT NULL, "permissions" integer DEFAULT NULL);
CREATE TABLE categories ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255) DEFAULT NULL, "description" varchar(255) DEFAULT NULL);
CREATE TABLE changes ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "change_type" integer DEFAULT NULL, "item_id" integer DEFAULT NULL, "person_id" integer DEFAULT NULL, "location_id" integer DEFAULT NULL, "old_value" varchar(255) DEFAULT NULL, "new_value" varchar(255) DEFAULT NULL, "effective_date" date DEFAULT NULL, "created_on" date DEFAULT NULL);
CREATE TABLE credit_cards ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "person_id" integer DEFAULT NULL, "card_type" varchar(255) DEFAULT NULL, "name_on_card" varchar(255) DEFAULT NULL, "card_number" varchar(255) DEFAULT NULL, "expiration_date" date DEFAULT NULL, "ccv" varchar(255) DEFAULT NULL, "created_on" date DEFAULT NULL);
CREATE TABLE items ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "tbid" varchar(255) DEFAULT NULL, "name" varchar(255) DEFAULT NULL, "description" text DEFAULT NULL, "person_id" integer DEFAULT NULL, "created_on" date DEFAULT NULL);
CREATE TABLE line_items ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "shopping_cart_id" integer DEFAULT NULL, "order_id" integer DEFAULT NULL, "sale_item_id" integer DEFAULT NULL, "quantity" integer DEFAULT NULL, "price_per_item" float DEFAULT NULL, "created_on" date DEFAULT NULL);
CREATE TABLE locations ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "description" varchar(255) DEFAULT NULL, "loc_type" varchar(255) DEFAULT NULL, "person_id" integer DEFAULT NULL, "item_id" integer DEFAULT NULL, "credit_card_id" integer DEFAULT NULL, "address_line_1" varchar(255) DEFAULT NULL, "address_line_2" varchar(255) DEFAULT NULL, "city" varchar(255) DEFAULT NULL, "state" varchar(255) DEFAULT NULL, "zip_code" varchar(255) DEFAULT NULL, "country" varchar(255) DEFAULT NULL, "latitude" varchar(255) DEFAULT NULL, "longitude" varchar(255) DEFAULT NULL, "altitude_feet" integer DEFAULT NULL);
CREATE TABLE orders ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "person_id" integer DEFAULT NULL, "shipping_location_id" integer DEFAULT NULL, "created_on" date DEFAULT NULL, "shipped_on" date DEFAULT NULL, "paid_on" date DEFAULT NULL);
CREATE TABLE people ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(255) DEFAULT NULL, "first_name" varchar(255) DEFAULT NULL, "middle_name" varchar(255) DEFAULT NULL, "last_name" varchar(255) DEFAULT NULL, "suffix" varchar(255) DEFAULT NULL, "birthday" date DEFAULT NULL, "email" varchar(255) DEFAULT NULL, "login" varchar(255) DEFAULT NULL, "hashed_password" text DEFAULT NULL, "created_on" date DEFAULT NULL, "notes" text DEFAULT NULL);
CREATE TABLE photos ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "path" varchar(255) DEFAULT NULL, "file_name" varchar(255) DEFAULT NULL, "url" varchar(255) DEFAULT NULL, "data" blob DEFAULT NULL, "content_type" varchar(255) DEFAULT NULL, "bytes" integer DEFAULT NULL, "width" integer DEFAULT NULL, "height" integer DEFAULT NULL, "caption" varchar(255) DEFAULT NULL, "photo_type" integer DEFAULT NULL, "location_id" integer DEFAULT NULL, "person_id" integer DEFAULT NULL, "item_id" integer DEFAULT NULL, "created_on" date DEFAULT NULL);
CREATE TABLE sale_items ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255) DEFAULT NULL, "description" varchar(255) DEFAULT NULL, "quantity_in_stock" integer DEFAULT NULL, "price" float DEFAULT NULL, "for_sale" varchar(255) DEFAULT NULL, "sale_price" float DEFAULT NULL, "status" integer DEFAULT NULL, "category_id" integer DEFAULT NULL);
CREATE TABLE schema_info (version integer);
CREATE TABLE shopping_carts ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "person_id" integer DEFAULT NULL, "created_on" date DEFAULT NULL, "modified_on" date DEFAULT NULL, "last_viewed" date DEFAULT NULL);
INSERT INTO schema_info (version) VALUES (12)